name: dart_commons
description: common functions for dart 
version: 0.1.0
author: ahmed beheiri
homepage: https://github.com/AhmedBeheiri/dart_commons
documentation: https://github.com/AhmedBeheiri/dart_commons

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.4
  flutter_phone_direct_caller:
    git:
      url: https://github.com/yanisalfian/flutter-phone-direct-caller.git
  url_launcher: ^5.5.0
  share: '>=0.6.4+3 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  module:
    androidX: true
    androidPackage: com.ahmed_beheiri.dart_common
    iosBundleIdentifier: com.ahmedbeheiri.dartCommon
